US001-AllJobRolesAPI-Created
SeanMcAvoy29/Belfast_Team2_Backend pull request #9
Opened 2023-09-14 08:59 UTC by mickey-dawson

2023-09-14 14:31 UTC, glenn-hamilton commented on src/main/java/org/kainos/ea/api/JobService.java
> +import org.kainos.ea.core.JobValidator;
The `JobValidator` class is missing

2023-09-14 14:31 UTC, glenn-hamilton commented on src/main/java/org/kainos/ea/api/JobService.java
> +import org.kainos.ea.cli.JobRequest;
The `JobRequest` class is missing

2023-09-14 14:31 UTC, glenn-hamilton commented on src/main/java/org/kainos/ea/api/JobService.java
> +import org.kainos.ea.client.FailedToCreateJobException;
The `FailedToCreateJobException` class is missing

2023-09-21 12:52 UTC, shaunganley requested changes
just a few things to tidy up

2023-09-21 12:52 UTC, shaunganley commented on pom.xml
> +        <mainClass>com.kainos.ea.WebServiceApplication</mainClass>
these changes might cause some issues with the build, I would leave as they are

2023-09-21 12:52 UTC, shaunganley commented on src/main/java/org/kainos/ea/api/JobService.java
> +    public JobService(org.kainos.ea.db.jobDao jobDao, DatabaseConnector connector) {
```suggestion
    public JobService(JobDao jobDao, DatabaseConnector connector) {
```

2023-09-21 12:52 UTC, shaunganley commented on src/main/java/org/kainos/ea/api/JobService.java
> +    public DatabaseConnector connector;
```suggestion
    private DatabaseConnector connector;
```

2023-09-21 12:52 UTC, shaunganley commented on src/main/java/org/kainos/ea/cli/JobRequest.java
> +public class JobRequest {
you don't need a job request object as you're not requesting any data on this endpoint

2023-09-21 12:52 UTC, shaunganley commented on src/main/java/org/kainos/ea/db/jobDao.java
> +    private DatabaseConnector databaseConnector = new DatabaseConnector();
shouldn't need this anymore as you're passing the connection in as a param

2023-09-21 12:52 UTC, shaunganley commented on src/main/java/org/kainos/ea/resources/JobController.java
> +            throw new RuntimeException(e);
add this to the above catch so it returns 500

2023-09-21 12:52 UTC, shaunganley commented on src/test/java/com/kainos/ea/service/JobServiceTest.java
> +    public void getAllJobRoles_shouldThrowSQLException_whenDaoThrowsSQLException() throws SQLException, DatabaseConnectionException {
add unit tests for the other exception scenarios as well

2023-09-21 13:09 UTC, shaunganley approved these changes

2023-09-25 09:53 UTC, shaunganley approved these changes

2023-09-27 12:10 UTC, shaunganley approved these changes

2023-09-28 12:36 UTC, merged